modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/Buuz135/HotOrNot/issues" #optional
[[mods]] #mandatory
modId="hotornot" #mandatory
version="${file.jarVersion}" #mandatory
displayName="HotOrNot" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/hot-or-not" #optional
authors="Buuz135, Affehund" #optional
description='''Is this hot?'''
